apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: jupyter
  name: jupyter
spec:
  ports:
  - name: "8888"
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    service: jupyter
status:
  loadBalancer: {}
