apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: scheduler-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
