apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: scheduler
  name: scheduler
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: scheduler
status:
  loadBalancer: {}
