apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: webserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: webserver
    spec:
      containers:
      - args:
        - webserver
        env:
        - name: LOAD_EX
          value: "n"
        - name: EXECUTOR
          value: Local
        - name: FERNET_KEY
          value: 9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        image: puckel/docker-airflow
        name: webserver
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: webserver-claim0
        - mountPath: /requirements.txt
          name: webserver-claim1
          readOnly: true
        - mountPath: /dojo
          name: webserver-claim2
      restartPolicy: Always
      volumes:
      - name: webserver-claim0
        persistentVolumeClaim:
          claimName: webserver-claim0
      - name: webserver-claim1
        persistentVolumeClaim:
          claimName: webserver-claim1
          readOnly: true
      - name: webserver-claim2
        persistentVolumeClaim:
          claimName: webserver-claim2
status: {}
