apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: webserver
  name: webserver
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: webserver
status:
  loadBalancer: {}
